version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - gosec
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
